# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
