# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_url_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
